// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tfnetwork.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_tfnetwork_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_tfnetwork_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "tensorflow/core/framework/graph.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_tfnetwork_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_tfnetwork_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_tfnetwork_2eproto;
namespace tesseract {
class TFNetworkModel;
class TFNetworkModelDefaultTypeInternal;
extern TFNetworkModelDefaultTypeInternal _TFNetworkModel_default_instance_;
}  // namespace tesseract
PROTOBUF_NAMESPACE_OPEN
template<> ::tesseract::TFNetworkModel* Arena::CreateMaybeMessage<::tesseract::TFNetworkModel>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tesseract {

// ===================================================================

class TFNetworkModel :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tesseract.TFNetworkModel) */ {
 public:
  TFNetworkModel();
  virtual ~TFNetworkModel();

  TFNetworkModel(const TFNetworkModel& from);
  TFNetworkModel(TFNetworkModel&& from) noexcept
    : TFNetworkModel() {
    *this = ::std::move(from);
  }

  inline TFNetworkModel& operator=(const TFNetworkModel& from) {
    CopyFrom(from);
    return *this;
  }
  inline TFNetworkModel& operator=(TFNetworkModel&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TFNetworkModel& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TFNetworkModel* internal_default_instance() {
    return reinterpret_cast<const TFNetworkModel*>(
               &_TFNetworkModel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TFNetworkModel& a, TFNetworkModel& b) {
    a.Swap(&b);
  }
  inline void Swap(TFNetworkModel* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TFNetworkModel* New() const final {
    return CreateMaybeMessage<TFNetworkModel>(nullptr);
  }

  TFNetworkModel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TFNetworkModel>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TFNetworkModel& from);
  void MergeFrom(const TFNetworkModel& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TFNetworkModel* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tesseract.TFNetworkModel";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_tfnetwork_2eproto);
    return ::descriptor_table_tfnetwork_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpecFieldNumber = 3,
    kImageInputFieldNumber = 11,
    kImageWidthsFieldNumber = 12,
    kImageHeightsFieldNumber = 13,
    kOutputLayerFieldNumber = 14,
    kGraphFieldNumber = 1,
    kGlobalStepFieldNumber = 2,
    kDepthFieldNumber = 4,
    kXSizeFieldNumber = 5,
    kYSizeFieldNumber = 6,
    kBatchSizeFieldNumber = 8,
    kNumClassesFieldNumber = 9,
    kUsingCtcFieldNumber = 10,
  };
  // string spec = 3;
  void clear_spec();
  const std::string& spec() const;
  void set_spec(const std::string& value);
  void set_spec(std::string&& value);
  void set_spec(const char* value);
  void set_spec(const char* value, size_t size);
  std::string* mutable_spec();
  std::string* release_spec();
  void set_allocated_spec(std::string* spec);
  private:
  const std::string& _internal_spec() const;
  void _internal_set_spec(const std::string& value);
  std::string* _internal_mutable_spec();
  public:

  // string image_input = 11;
  void clear_image_input();
  const std::string& image_input() const;
  void set_image_input(const std::string& value);
  void set_image_input(std::string&& value);
  void set_image_input(const char* value);
  void set_image_input(const char* value, size_t size);
  std::string* mutable_image_input();
  std::string* release_image_input();
  void set_allocated_image_input(std::string* image_input);
  private:
  const std::string& _internal_image_input() const;
  void _internal_set_image_input(const std::string& value);
  std::string* _internal_mutable_image_input();
  public:

  // string image_widths = 12;
  void clear_image_widths();
  const std::string& image_widths() const;
  void set_image_widths(const std::string& value);
  void set_image_widths(std::string&& value);
  void set_image_widths(const char* value);
  void set_image_widths(const char* value, size_t size);
  std::string* mutable_image_widths();
  std::string* release_image_widths();
  void set_allocated_image_widths(std::string* image_widths);
  private:
  const std::string& _internal_image_widths() const;
  void _internal_set_image_widths(const std::string& value);
  std::string* _internal_mutable_image_widths();
  public:

  // string image_heights = 13;
  void clear_image_heights();
  const std::string& image_heights() const;
  void set_image_heights(const std::string& value);
  void set_image_heights(std::string&& value);
  void set_image_heights(const char* value);
  void set_image_heights(const char* value, size_t size);
  std::string* mutable_image_heights();
  std::string* release_image_heights();
  void set_allocated_image_heights(std::string* image_heights);
  private:
  const std::string& _internal_image_heights() const;
  void _internal_set_image_heights(const std::string& value);
  std::string* _internal_mutable_image_heights();
  public:

  // string output_layer = 14;
  void clear_output_layer();
  const std::string& output_layer() const;
  void set_output_layer(const std::string& value);
  void set_output_layer(std::string&& value);
  void set_output_layer(const char* value);
  void set_output_layer(const char* value, size_t size);
  std::string* mutable_output_layer();
  std::string* release_output_layer();
  void set_allocated_output_layer(std::string* output_layer);
  private:
  const std::string& _internal_output_layer() const;
  void _internal_set_output_layer(const std::string& value);
  std::string* _internal_mutable_output_layer();
  public:

  // .tensorflow.GraphDef graph = 1;
  bool has_graph() const;
  private:
  bool _internal_has_graph() const;
  public:
  void clear_graph();
  const ::tensorflow::GraphDef& graph() const;
  ::tensorflow::GraphDef* release_graph();
  ::tensorflow::GraphDef* mutable_graph();
  void set_allocated_graph(::tensorflow::GraphDef* graph);
  private:
  const ::tensorflow::GraphDef& _internal_graph() const;
  ::tensorflow::GraphDef* _internal_mutable_graph();
  public:

  // int64 global_step = 2;
  void clear_global_step();
  ::PROTOBUF_NAMESPACE_ID::int64 global_step() const;
  void set_global_step(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_global_step() const;
  void _internal_set_global_step(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 depth = 4;
  void clear_depth();
  ::PROTOBUF_NAMESPACE_ID::int32 depth() const;
  void set_depth(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_depth() const;
  void _internal_set_depth(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 x_size = 5;
  void clear_x_size();
  ::PROTOBUF_NAMESPACE_ID::int32 x_size() const;
  void set_x_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_x_size() const;
  void _internal_set_x_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 y_size = 6;
  void clear_y_size();
  ::PROTOBUF_NAMESPACE_ID::int32 y_size() const;
  void set_y_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_y_size() const;
  void _internal_set_y_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 batch_size = 8;
  void clear_batch_size();
  ::PROTOBUF_NAMESPACE_ID::int32 batch_size() const;
  void set_batch_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_batch_size() const;
  void _internal_set_batch_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 num_classes = 9;
  void clear_num_classes();
  ::PROTOBUF_NAMESPACE_ID::int32 num_classes() const;
  void set_num_classes(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_num_classes() const;
  void _internal_set_num_classes(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // bool using_ctc = 10;
  void clear_using_ctc();
  bool using_ctc() const;
  void set_using_ctc(bool value);
  private:
  bool _internal_using_ctc() const;
  void _internal_set_using_ctc(bool value);
  public:

  // @@protoc_insertion_point(class_scope:tesseract.TFNetworkModel)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr spec_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_input_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_widths_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_heights_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr output_layer_;
  ::tensorflow::GraphDef* graph_;
  ::PROTOBUF_NAMESPACE_ID::int64 global_step_;
  ::PROTOBUF_NAMESPACE_ID::int32 depth_;
  ::PROTOBUF_NAMESPACE_ID::int32 x_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 y_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 batch_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 num_classes_;
  bool using_ctc_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_tfnetwork_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TFNetworkModel

// .tensorflow.GraphDef graph = 1;
inline bool TFNetworkModel::_internal_has_graph() const {
  return this != internal_default_instance() && graph_ != nullptr;
}
inline bool TFNetworkModel::has_graph() const {
  return _internal_has_graph();
}
inline const ::tensorflow::GraphDef& TFNetworkModel::_internal_graph() const {
  const ::tensorflow::GraphDef* p = graph_;
  return p != nullptr ? *p : *reinterpret_cast<const ::tensorflow::GraphDef*>(
      &::tensorflow::_GraphDef_default_instance_);
}
inline const ::tensorflow::GraphDef& TFNetworkModel::graph() const {
  // @@protoc_insertion_point(field_get:tesseract.TFNetworkModel.graph)
  return _internal_graph();
}
inline ::tensorflow::GraphDef* TFNetworkModel::release_graph() {
  // @@protoc_insertion_point(field_release:tesseract.TFNetworkModel.graph)
  
  ::tensorflow::GraphDef* temp = graph_;
  graph_ = nullptr;
  return temp;
}
inline ::tensorflow::GraphDef* TFNetworkModel::_internal_mutable_graph() {
  
  if (graph_ == nullptr) {
    auto* p = CreateMaybeMessage<::tensorflow::GraphDef>(GetArenaNoVirtual());
    graph_ = p;
  }
  return graph_;
}
inline ::tensorflow::GraphDef* TFNetworkModel::mutable_graph() {
  // @@protoc_insertion_point(field_mutable:tesseract.TFNetworkModel.graph)
  return _internal_mutable_graph();
}
inline void TFNetworkModel::set_allocated_graph(::tensorflow::GraphDef* graph) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(graph_);
  }
  if (graph) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(graph)->GetArena();
    if (message_arena != submessage_arena) {
      graph = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, graph, submessage_arena);
    }
    
  } else {
    
  }
  graph_ = graph;
  // @@protoc_insertion_point(field_set_allocated:tesseract.TFNetworkModel.graph)
}

// int64 global_step = 2;
inline void TFNetworkModel::clear_global_step() {
  global_step_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TFNetworkModel::_internal_global_step() const {
  return global_step_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TFNetworkModel::global_step() const {
  // @@protoc_insertion_point(field_get:tesseract.TFNetworkModel.global_step)
  return _internal_global_step();
}
inline void TFNetworkModel::_internal_set_global_step(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  global_step_ = value;
}
inline void TFNetworkModel::set_global_step(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_global_step(value);
  // @@protoc_insertion_point(field_set:tesseract.TFNetworkModel.global_step)
}

// string spec = 3;
inline void TFNetworkModel::clear_spec() {
  spec_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& TFNetworkModel::spec() const {
  // @@protoc_insertion_point(field_get:tesseract.TFNetworkModel.spec)
  return _internal_spec();
}
inline void TFNetworkModel::set_spec(const std::string& value) {
  _internal_set_spec(value);
  // @@protoc_insertion_point(field_set:tesseract.TFNetworkModel.spec)
}
inline std::string* TFNetworkModel::mutable_spec() {
  // @@protoc_insertion_point(field_mutable:tesseract.TFNetworkModel.spec)
  return _internal_mutable_spec();
}
inline const std::string& TFNetworkModel::_internal_spec() const {
  return spec_.GetNoArena();
}
inline void TFNetworkModel::_internal_set_spec(const std::string& value) {
  
  spec_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void TFNetworkModel::set_spec(std::string&& value) {
  
  spec_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tesseract.TFNetworkModel.spec)
}
inline void TFNetworkModel::set_spec(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  spec_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tesseract.TFNetworkModel.spec)
}
inline void TFNetworkModel::set_spec(const char* value, size_t size) {
  
  spec_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tesseract.TFNetworkModel.spec)
}
inline std::string* TFNetworkModel::_internal_mutable_spec() {
  
  return spec_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TFNetworkModel::release_spec() {
  // @@protoc_insertion_point(field_release:tesseract.TFNetworkModel.spec)
  
  return spec_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TFNetworkModel::set_allocated_spec(std::string* spec) {
  if (spec != nullptr) {
    
  } else {
    
  }
  spec_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), spec);
  // @@protoc_insertion_point(field_set_allocated:tesseract.TFNetworkModel.spec)
}

// int32 depth = 4;
inline void TFNetworkModel::clear_depth() {
  depth_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TFNetworkModel::_internal_depth() const {
  return depth_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TFNetworkModel::depth() const {
  // @@protoc_insertion_point(field_get:tesseract.TFNetworkModel.depth)
  return _internal_depth();
}
inline void TFNetworkModel::_internal_set_depth(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  depth_ = value;
}
inline void TFNetworkModel::set_depth(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_depth(value);
  // @@protoc_insertion_point(field_set:tesseract.TFNetworkModel.depth)
}

// int32 x_size = 5;
inline void TFNetworkModel::clear_x_size() {
  x_size_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TFNetworkModel::_internal_x_size() const {
  return x_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TFNetworkModel::x_size() const {
  // @@protoc_insertion_point(field_get:tesseract.TFNetworkModel.x_size)
  return _internal_x_size();
}
inline void TFNetworkModel::_internal_set_x_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  x_size_ = value;
}
inline void TFNetworkModel::set_x_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_x_size(value);
  // @@protoc_insertion_point(field_set:tesseract.TFNetworkModel.x_size)
}

// int32 y_size = 6;
inline void TFNetworkModel::clear_y_size() {
  y_size_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TFNetworkModel::_internal_y_size() const {
  return y_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TFNetworkModel::y_size() const {
  // @@protoc_insertion_point(field_get:tesseract.TFNetworkModel.y_size)
  return _internal_y_size();
}
inline void TFNetworkModel::_internal_set_y_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  y_size_ = value;
}
inline void TFNetworkModel::set_y_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_y_size(value);
  // @@protoc_insertion_point(field_set:tesseract.TFNetworkModel.y_size)
}

// int32 batch_size = 8;
inline void TFNetworkModel::clear_batch_size() {
  batch_size_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TFNetworkModel::_internal_batch_size() const {
  return batch_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TFNetworkModel::batch_size() const {
  // @@protoc_insertion_point(field_get:tesseract.TFNetworkModel.batch_size)
  return _internal_batch_size();
}
inline void TFNetworkModel::_internal_set_batch_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  batch_size_ = value;
}
inline void TFNetworkModel::set_batch_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_batch_size(value);
  // @@protoc_insertion_point(field_set:tesseract.TFNetworkModel.batch_size)
}

// int32 num_classes = 9;
inline void TFNetworkModel::clear_num_classes() {
  num_classes_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TFNetworkModel::_internal_num_classes() const {
  return num_classes_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TFNetworkModel::num_classes() const {
  // @@protoc_insertion_point(field_get:tesseract.TFNetworkModel.num_classes)
  return _internal_num_classes();
}
inline void TFNetworkModel::_internal_set_num_classes(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  num_classes_ = value;
}
inline void TFNetworkModel::set_num_classes(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_num_classes(value);
  // @@protoc_insertion_point(field_set:tesseract.TFNetworkModel.num_classes)
}

// bool using_ctc = 10;
inline void TFNetworkModel::clear_using_ctc() {
  using_ctc_ = false;
}
inline bool TFNetworkModel::_internal_using_ctc() const {
  return using_ctc_;
}
inline bool TFNetworkModel::using_ctc() const {
  // @@protoc_insertion_point(field_get:tesseract.TFNetworkModel.using_ctc)
  return _internal_using_ctc();
}
inline void TFNetworkModel::_internal_set_using_ctc(bool value) {
  
  using_ctc_ = value;
}
inline void TFNetworkModel::set_using_ctc(bool value) {
  _internal_set_using_ctc(value);
  // @@protoc_insertion_point(field_set:tesseract.TFNetworkModel.using_ctc)
}

// string image_input = 11;
inline void TFNetworkModel::clear_image_input() {
  image_input_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& TFNetworkModel::image_input() const {
  // @@protoc_insertion_point(field_get:tesseract.TFNetworkModel.image_input)
  return _internal_image_input();
}
inline void TFNetworkModel::set_image_input(const std::string& value) {
  _internal_set_image_input(value);
  // @@protoc_insertion_point(field_set:tesseract.TFNetworkModel.image_input)
}
inline std::string* TFNetworkModel::mutable_image_input() {
  // @@protoc_insertion_point(field_mutable:tesseract.TFNetworkModel.image_input)
  return _internal_mutable_image_input();
}
inline const std::string& TFNetworkModel::_internal_image_input() const {
  return image_input_.GetNoArena();
}
inline void TFNetworkModel::_internal_set_image_input(const std::string& value) {
  
  image_input_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void TFNetworkModel::set_image_input(std::string&& value) {
  
  image_input_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tesseract.TFNetworkModel.image_input)
}
inline void TFNetworkModel::set_image_input(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  image_input_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tesseract.TFNetworkModel.image_input)
}
inline void TFNetworkModel::set_image_input(const char* value, size_t size) {
  
  image_input_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tesseract.TFNetworkModel.image_input)
}
inline std::string* TFNetworkModel::_internal_mutable_image_input() {
  
  return image_input_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TFNetworkModel::release_image_input() {
  // @@protoc_insertion_point(field_release:tesseract.TFNetworkModel.image_input)
  
  return image_input_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TFNetworkModel::set_allocated_image_input(std::string* image_input) {
  if (image_input != nullptr) {
    
  } else {
    
  }
  image_input_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), image_input);
  // @@protoc_insertion_point(field_set_allocated:tesseract.TFNetworkModel.image_input)
}

// string image_widths = 12;
inline void TFNetworkModel::clear_image_widths() {
  image_widths_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& TFNetworkModel::image_widths() const {
  // @@protoc_insertion_point(field_get:tesseract.TFNetworkModel.image_widths)
  return _internal_image_widths();
}
inline void TFNetworkModel::set_image_widths(const std::string& value) {
  _internal_set_image_widths(value);
  // @@protoc_insertion_point(field_set:tesseract.TFNetworkModel.image_widths)
}
inline std::string* TFNetworkModel::mutable_image_widths() {
  // @@protoc_insertion_point(field_mutable:tesseract.TFNetworkModel.image_widths)
  return _internal_mutable_image_widths();
}
inline const std::string& TFNetworkModel::_internal_image_widths() const {
  return image_widths_.GetNoArena();
}
inline void TFNetworkModel::_internal_set_image_widths(const std::string& value) {
  
  image_widths_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void TFNetworkModel::set_image_widths(std::string&& value) {
  
  image_widths_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tesseract.TFNetworkModel.image_widths)
}
inline void TFNetworkModel::set_image_widths(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  image_widths_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tesseract.TFNetworkModel.image_widths)
}
inline void TFNetworkModel::set_image_widths(const char* value, size_t size) {
  
  image_widths_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tesseract.TFNetworkModel.image_widths)
}
inline std::string* TFNetworkModel::_internal_mutable_image_widths() {
  
  return image_widths_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TFNetworkModel::release_image_widths() {
  // @@protoc_insertion_point(field_release:tesseract.TFNetworkModel.image_widths)
  
  return image_widths_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TFNetworkModel::set_allocated_image_widths(std::string* image_widths) {
  if (image_widths != nullptr) {
    
  } else {
    
  }
  image_widths_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), image_widths);
  // @@protoc_insertion_point(field_set_allocated:tesseract.TFNetworkModel.image_widths)
}

// string image_heights = 13;
inline void TFNetworkModel::clear_image_heights() {
  image_heights_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& TFNetworkModel::image_heights() const {
  // @@protoc_insertion_point(field_get:tesseract.TFNetworkModel.image_heights)
  return _internal_image_heights();
}
inline void TFNetworkModel::set_image_heights(const std::string& value) {
  _internal_set_image_heights(value);
  // @@protoc_insertion_point(field_set:tesseract.TFNetworkModel.image_heights)
}
inline std::string* TFNetworkModel::mutable_image_heights() {
  // @@protoc_insertion_point(field_mutable:tesseract.TFNetworkModel.image_heights)
  return _internal_mutable_image_heights();
}
inline const std::string& TFNetworkModel::_internal_image_heights() const {
  return image_heights_.GetNoArena();
}
inline void TFNetworkModel::_internal_set_image_heights(const std::string& value) {
  
  image_heights_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void TFNetworkModel::set_image_heights(std::string&& value) {
  
  image_heights_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tesseract.TFNetworkModel.image_heights)
}
inline void TFNetworkModel::set_image_heights(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  image_heights_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tesseract.TFNetworkModel.image_heights)
}
inline void TFNetworkModel::set_image_heights(const char* value, size_t size) {
  
  image_heights_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tesseract.TFNetworkModel.image_heights)
}
inline std::string* TFNetworkModel::_internal_mutable_image_heights() {
  
  return image_heights_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TFNetworkModel::release_image_heights() {
  // @@protoc_insertion_point(field_release:tesseract.TFNetworkModel.image_heights)
  
  return image_heights_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TFNetworkModel::set_allocated_image_heights(std::string* image_heights) {
  if (image_heights != nullptr) {
    
  } else {
    
  }
  image_heights_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), image_heights);
  // @@protoc_insertion_point(field_set_allocated:tesseract.TFNetworkModel.image_heights)
}

// string output_layer = 14;
inline void TFNetworkModel::clear_output_layer() {
  output_layer_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& TFNetworkModel::output_layer() const {
  // @@protoc_insertion_point(field_get:tesseract.TFNetworkModel.output_layer)
  return _internal_output_layer();
}
inline void TFNetworkModel::set_output_layer(const std::string& value) {
  _internal_set_output_layer(value);
  // @@protoc_insertion_point(field_set:tesseract.TFNetworkModel.output_layer)
}
inline std::string* TFNetworkModel::mutable_output_layer() {
  // @@protoc_insertion_point(field_mutable:tesseract.TFNetworkModel.output_layer)
  return _internal_mutable_output_layer();
}
inline const std::string& TFNetworkModel::_internal_output_layer() const {
  return output_layer_.GetNoArena();
}
inline void TFNetworkModel::_internal_set_output_layer(const std::string& value) {
  
  output_layer_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void TFNetworkModel::set_output_layer(std::string&& value) {
  
  output_layer_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tesseract.TFNetworkModel.output_layer)
}
inline void TFNetworkModel::set_output_layer(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  output_layer_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tesseract.TFNetworkModel.output_layer)
}
inline void TFNetworkModel::set_output_layer(const char* value, size_t size) {
  
  output_layer_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tesseract.TFNetworkModel.output_layer)
}
inline std::string* TFNetworkModel::_internal_mutable_output_layer() {
  
  return output_layer_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TFNetworkModel::release_output_layer() {
  // @@protoc_insertion_point(field_release:tesseract.TFNetworkModel.output_layer)
  
  return output_layer_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TFNetworkModel::set_allocated_output_layer(std::string* output_layer) {
  if (output_layer != nullptr) {
    
  } else {
    
  }
  output_layer_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), output_layer);
  // @@protoc_insertion_point(field_set_allocated:tesseract.TFNetworkModel.output_layer)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace tesseract

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_tfnetwork_2eproto
